# Generated by Django 4.1.5 on 2023-03-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_owner",
            field=models.BooleanField(default=True),
        ),
    ]
