# Generated by Django 4.1.7 on 2023-03-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetail',
            name='is_property_active',
            field=models.BooleanField(default=True),
        ),
    ]
