# Generated by Django 4.1.7 on 2023-03-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyManager', '0003_alter_propertydetail_adhar_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetail',
            name='adhar_pic',
            field=models.FileField(default=None, null=True, upload_to='adhar_card'),
        ),
    ]
