# Generated by Django 4.1.7 on 2023-03-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyManager', '0008_alter_propertydetail_adhar_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetail',
            name='adhar_pic',
            field=models.ImageField(default=True, null=True, upload_to='adhar_card'),
        ),
    ]
