# Generated by Django 4.1.7 on 2023-03-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyManager', '0009_alter_propertydetail_adhar_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetail',
            name='adhar_pic',
            field=models.ImageField(default=None, null=True, upload_to='adhar_card'),
        ),
    ]
